<a href="https://colab.research.google.com/github/Sakshii0906/DATA-SCIENCE-PRACTICALS/blob/main/Deep_Learning_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#                                                                       **LAB-1**

### Q1. Create a 2x2 tensor of random values in PyTorch and print its shape.

In [6]:
import torch
random_tensor =torch.rand((2,2))
print(random_tensor)
print("shape of tensor:\n",random_tensor.shape)

tensor([[0.2041, 0.4692],
        [0.7933, 0.2976]])
shape of tensor:
 torch.Size([2, 2])


### Q2. In PyTorch, create a 1D tensor with values [1.0, 2.0, 3.0] and [4.0, 5.0, 6.0], then compute:
### (a) Element-wise addition (b) Dot product

In [ ]:
tensor1 = torch.tensor([1.0,2.0,3.0])
tensor2 = torch.tensor([4.0,5.0,6.0])
print("addition:\n",tensor1+tensor2)
print("dot product:\n",torch.dot(tensor1,tensor2))

addition:
 tensor([5., 7., 9.])
dot product:
 tensor(32.)


### Q3. Convert a NumPy array [[10, 20], [30, 40]] into a PyTorch tensor, and convert it back to a NumPy array.

In [ ]:
import numpy as np
numpy_array = np.array([[10, 20], [30, 40]])
print("numpy_array:\n",numpy_array)
tensor_array =torch.from_numpy(numpy_array)
print("Converted_array:\n",tensor_array)
numpy_array_back = tensor_array.numpy()
print("numpy_array_back:\n",numpy_array_back )

numpy_array:
 [[10 20]
 [30 40]]
Converted_array:
 tensor([[10, 20],
        [30, 40]])
numpy_array_back:
 [[10 20]
 [30 40]]


### Q4. In TensorFlow, create a 3x3 tensor filled with ones. Reshape it to a 1D tensor of size 9.

In [ ]:
import tensorflow as tf
tensor = tf.ones((3,3))
print("Tensor:\n",tensor)
reshaped_tensor = tf.reshape(tensor,(9))
print("reshaped_tensor:\n",reshaped_tensor)

Tensor:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
reshaped_tensor:
 tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(9,), dtype=float32)


### Q5. In TensorFlow, define two 1D tensors and compute: (a) Their sum (b) Their dot product

In [ ]:
tensor1 = tf.constant([1.0,2.0,3.0])
tensor2 = tf.constant([4.0,5.0,6.0])
print("addition:\n",tensor1+tensor2)
print("dot product:\n",tf.tensordot(tensor1,tensor2,axes=1))

addition:
 tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
dot product:
 tf.Tensor(32.0, shape=(), dtype=float32)


### Q6. Convert the NumPy array [[5, 6], [7, 8]] into a TensorFlow tensor and back to NumPy.

In [ ]:
numpy_array = np.array([[5,6],[7,8]])
print("numpy array:\n",numpy_array)
tensor_array = tf.convert_to_tensor(numpy_array)
print("tensor_array:\n",tensor_array)
numpy_array_back = tensor_array.numpy()
print("converted numpy:\n",numpy_array_back)

numpy array:
 [[5 6]
 [7 8]]
tensor_array:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int64)
converted numpy:
 [[5 6]
 [7 8]]


# **VIVA QUESTIONS**

### **Q1.What is the purpose of .view(9) and tf.reshape()?**
### Ans.Both .view(9) in PyTorch and tf.reshape() in TensorFlow are used to reshape tensors-changing their shape (rows/columns) without changing the data.
### .view(9) reshapes the PyTorch tensor to a 1D tensor of 9 elements.

### tf.reshape() reshapes the TensorFlow tensor similarly.
### This is helpful when input data needs to be fed into a model that expects a specific shape.



### **Q2.What does the dot product result tell you?**

### ANS.The dot product gives a single number that shows how similar or aligned two vectors are. If the result is positive, the vectors point in a similar direction; if it's zero, they are perpendicular (no similarity); and if it's negative, they point in opposite directions. In deep learning, it helps measure similarity, projection, or perform weighted sums

### **### Q3. How does torch.from_numpy() differ from tf.convert_to_tensor()?**
### ANS.torch.from_numpy() creates a PyTorch tensor that shares memory with the original NumPy array. So, changes in one will affect the other.
### On the other hand, tf.convert_to_tensor() creates a TensorFlow tensor from a NumPy array or list, but it usually copies the data, so changes in the original array do not affect the tensor.

### **Q4. Why is .numpy() used in both PyTorch and TensorFlow?**
### Ans. .numpy() is used to convert a tensor into a NumPy array. This is useful because:

### NumPy has many built-in functions for math and analysis.
### It’s easier to use Python libraries like matplotlib, scikit-learn, etc., with NumPy arrays.
### You can export or manipulate the tensor in a familiar format.


### **Q5. What is the data type (dtype) of the tensors created?**
### Ans. The dtype of a tensor tells us what type of data it holds — like integers (int), floating-point numbers (float), booleans (bool), etc.
### By default:
### PyTorch tensors are usually created with torch.float32.
### TensorFlow tensors are usually created with tf.float32.

### **Q6.Can you reshape a 3×3 tensor to size 6? Why or why not?**

### Ans.No, we cannot reshape a 3×3 tensor (which has 9 elements) to size 6, because reshaping does not change the data—it only changes the shape.
### To reshape a tensor, the total number of elements must remain the same.