In [2]:
import numpy as np
ar1 = np.arange(10,dtype=float)
print(ar1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [3]:
np.__version__

'1.21.5'

In [5]:
arr = np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
l = [1,2,3,4,5]
l


[1, 2, 3, 4, 5]

In [15]:
l2=[x for x in range(0,10)]
l2



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l3=[str(x) for x in l2]
l3


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [18]:
l4=[x for x in range(0,10,2)]
l4

[0, 2, 4, 6, 8]

In [19]:
l4 = [x**2 for x in range(0,10)]
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [21]:
import array

In [22]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array
    
    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |  
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |  
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined

In [26]:
arr = array.array('i',l2)
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr = array.array('f',l2)
arr

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [29]:
type(arr)

array.array

In [33]:
arr = array.array('i',[x**2 for x in l2])
arr

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [34]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
np.array([x-3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [37]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [38]:
np.array([1,2,3,4],dtype = 'float')

array([1., 2., 3., 4.])

In [39]:
np.array([1,2,3,4],dtype = 'str')

array(['1', '2', '3', '4'], dtype='<U1')

In [40]:
np.array([1,2,3,4],dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [43]:
list = [[1,2,3,4],[4,5,6,7]]
list

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [46]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
lc =[range(i,i+3) for i in [1,3]]
lc

[range(1, 4), range(3, 6)]

In [49]:
np.array(lc)

array([[1, 2, 3],
       [3, 4, 5]])

In [50]:
lc =[range(i,i+3) for i in [1,9]]
lc

[range(1, 4), range(9, 12)]

In [51]:
np.array(lc)

array([[ 1,  2,  3],
       [ 9, 10, 11]])

In [52]:
lc =[range(i,i+3) for i in [1,9,3]]
lc

[range(1, 4), range(9, 12), range(3, 6)]

In [53]:
np.array(lc)

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [ 3,  4,  5]])

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
np.zeros([2,2],dtype = 'int32')

array([[0, 0],
       [0, 0]])

In [57]:
np.zeros([10,10],dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
np.zeros([3,4],dtype = 'int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
arr = np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
arr[1:9,1:9]= 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
arr[2:8,2:8]=8
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 9., 9., 9., 9., 9., 9., 9., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
arr[3:7,3:7]=7
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 9., 9., 9., 9., 9., 9., 9., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
arr[4:6,4:6]=6
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 9., 9., 9., 9., 9., 9., 9., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 6., 6., 7., 8., 1., 1.],
       [1., 9., 8., 7., 6., 6., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
ar = np.arange(0,9,dtype='float').reshape(3,3)
ar

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [86]:
ar[:] = 3.14
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [90]:
np.full((3,4),'abc')

array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [92]:
#identity matrix
np.eye?

In [93]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [95]:
np.transpose(np.eye(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#list
#list comprehesion
#array modules(imported library array)
#numpy array(zeros,ones,full,eye,arange)
#reshape
#indexing