In [1]:
import pandas as pd


In [4]:
a = pd.Series(data =["maths",calculus]
print(a)

SyntaxError: positional argument follows keyword argument (1605455344.py, line 1)

In [5]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
s1.values

array([1, 2, 3, 4, 5], dtype=int64)

In [9]:
s1.value_counts

<bound method IndexOpsMixin.value_counts of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

In [13]:
import numpy as np
marks = np.arange(30,50,2)
marks

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [14]:
s = pd.Series(marks)
s

0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int32

In [17]:
dmarks={'jiya':90,'tisha':30,'abhi':60}
dmarks

{'jiya': 90, 'tisha': 30, 'abhi': 60}

In [18]:
j = pd.Series(dmarks)
j

jiya     90
tisha    30
abhi     60
dtype: int64

In [20]:
j.values

array([90, 30, 60], dtype=int64)

In [21]:
j.index

Index(['jiya', 'tisha', 'abhi'], dtype='object')

In [22]:
s2 = pd.Series(index=['x','y','z'],data=[3,4,5])
s2

x    3
y    4
z    5
dtype: int64

In [24]:
display(s2.values,s2.index)

array([3, 4, 5], dtype=int64)

Index(['x', 'y', 'z'], dtype='object')

In [25]:
s3 = pd.Series(['x','y','z'],[3,4,5])
s3

3    x
4    y
5    z
dtype: object

In [26]:
a=s3.values,s3.index
a

(array(['x', 'y', 'z'], dtype=object), Int64Index([3, 4, 5], dtype='int64'))

In [27]:
s2.y

4

In [29]:
s2[:'y']

x    3
y    4
dtype: int64

In [34]:
display(s2['y':], s2[:2])

y    4
z    5
dtype: int64

x    3
y    4
dtype: int64

In [31]:
s

0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int32

In [33]:
s[2:8]

2    34
3    36
4    38
5    40
6    42
7    44
dtype: int32

In [37]:
a = {'hina':'a','diya':'c'}
a

{'hina': 'a', 'diya': 'c'}

In [39]:
s = pd.Series(a)
s

hina    a
diya    c
dtype: object

In [40]:
s.index

Index(['hina', 'diya'], dtype='object')

In [41]:
s.values

array(['a', 'c'], dtype=object)

In [44]:
data=['A+','B+','A']
index=['jiya','tiya','niya']
pd.Series(data,index)

jiya    A+
tiya    B+
niya     A
dtype: object

In [45]:
pd.Series(index,data)

A+    jiya
B+    tiya
A     niya
dtype: object

In [46]:
display(pd.Series(ind,data),
       pd.Series(ind,data).index,
       pd.Series(ind,data).values)

A+    jiya
B+    tiya
A     niya
dtype: object

Index(['A+', 'B+', 'A'], dtype='object')

array(['jiya', 'tiya', 'niya'], dtype=object)

In [1]:
a =["sakshi",10,"jiya",20,"maitri",30]
a

['sakshi', 10, 'jiya', 20, 'maitri', 30]

In [6]:
import pandas as pd
b = pd.Series(a)
print(b)

0    sakshi
1        10
2      jiya
3        20
4    maitri
5        30
dtype: object


In [7]:
c = ("calculus",90,"bst","eco",20)
c

('calculus', 90, 'bst', 'eco', 20)

In [11]:
q = pd.Series(c)
q

0    calculus
1          90
2         bst
3         eco
4          20
dtype: object

In [8]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

['apple', 'banana', 'mango']


In [9]:
s = pd.Series(fruits)
s

0     apple
1    banana
2    cherry
3      kiwi
4     mango
dtype: object

In [12]:
pd.DataFrame?


In [18]:
pd.DataFrame({'riya':[54,53],'jiya':[89,34]},index=['python','FDS'])

riya  jiya
python    54    89
FDS       53    34

In [19]:
pd.DataFrame([[24,23],[45,56]],columns=['A','B'],index=['pyhton','FDS'])

A   B
pyhton  24  23
FDS     45  56

In [20]:
import numpy as np

In [30]:
np.random.seed(9)
marks=pd.DataFrame(np.random.randint(0,30,(3,3)),index=['jiya','tisha','riya'],columns=['py','fds','cai'])
marks

py  fds  cai
jiya   28   21   22
tisha  24   27   22
riya   29    1   22

In [31]:
marks.columns

Index(['py', 'fds', 'cai'], dtype='object')

In [32]:
marks.values

array([[28, 21, 22],
       [24, 27, 22],
       [29,  1, 22]])

In [33]:
marks.index

Index(['jiya', 'tisha', 'riya'], dtype='object')

In [34]:
marks['py']

jiya     28
tisha    24
riya     29
Name: py, dtype: int32

In [35]:
marks['fds']

jiya     21
tisha    27
riya      1
Name: fds, dtype: int32

In [38]:
pd.DataFrame(np.arange(0,10),index=['jiya','sakshi','maitri'])

ValueError: Shape of passed values is (5, 1), indices imply (3, 1)

In [40]:
marks['Total']=marks['py']+marks['fds']+marks['cai']
marks

py  fds  cai  Total
jiya   28   21   22     71
tisha  24   27   22     73
riya   29    1   22     52

In [42]:
marks['percentage']=marks['Total']/300
marks

py  fds  cai  Total  percentage
jiya   28   21   22     71    0.236667
tisha  24   27   22     73    0.243333
riya   29    1   22     52    0.173333

In [ ]:
#indexing & selection

In [44]:
marks[['py','fds']]

py  fds
jiya   28   21
tisha  24   27
riya   29    1

In [ ]:
marks.loc
marks.iloc
marks.ix

In [47]:
pd.DataFrame.loc?

In [49]:
pd.DataFrame.iloc?

In [52]:
marks.loc['riya']

py            29.000000
fds            1.000000
cai           22.000000
Total         52.000000
percentage     0.173333
Name: riya, dtype: float64

In [55]:
marks.loc['riya','py':'cai']

py     29.0
fds     1.0
cai    22.0
Name: riya, dtype: float64

In [56]:
marks.loc[:'tisha']

py  fds  cai  Total  percentage
jiya   28   21   22     71    0.236667
tisha  24   27   22     73    0.243333

In [57]:
marks.loc[:'tisha',['py','fds']]

py  fds
jiya   28   21
tisha  24   27

In [58]:
marks.loc[:'tisha','fds':]

fds  cai  Total  percentage
jiya    21   22     71    0.236667
tisha   27   22     73    0.243333

In [60]:
marks.loc['tisha',['fds','cai']]

fds    27.0
cai    22.0
Name: tisha, dtype: float64

In [61]:
marks.loc['tisha','fds':'cai']

fds    27.0
cai    22.0
Name: tisha, dtype: float64

In [62]:
marks.iloc[2]

py            29.000000
fds            1.000000
cai           22.000000
Total         52.000000
percentage     0.173333
Name: riya, dtype: float64

In [63]:
marks.iloc[:2]

py  fds  cai  Total  percentage
jiya   28   21   22     71    0.236667
tisha  24   27   22     73    0.243333

In [64]:
marks.iloc[:2,0:3]

py  fds  cai
jiya   28   21   22
tisha  24   27   22

In [67]:
marks.iloc[:,3]

jiya     71
tisha    73
riya     52
Name: Total, dtype: int32

In [68]:
marks.iloc[:,0]

jiya     28
tisha    24
riya     29
Name: py, dtype: int32

In [69]:
marks.iloc[:,0:1]

py
jiya   28
tisha  24
riya   29

In [70]:
marks.iloc[:,0] >25

jiya      True
tisha    False
riya      True
Name: py, dtype: bool

In [71]:
marks[marks.py>25]

py  fds  cai  Total  percentage
jiya  28   21   22     71    0.236667
riya  29    1   22     52    0.173333

In [74]:
np.random.seed(9)
marks=pd.DataFrame(np.random.randint(0,100,(10,3)),index=['jiya','tisha','riya','om','maitri','shree','niya','tiya','kiya','priya'],columns=['py','fds','cai'])
marks

py  fds  cai
jiya    92   54   56
tisha   22   65   22
riya    52   59   40
om      91   33   93
maitri  92    0   60
shree   59   88   74
niya    56   93   62
tiya    12   18   86
kiya    56    1   56
priya   99   11   37

In [80]:
marks[marks['py']<40]=41
marks


py  fds  cai
jiya    92   54   56
tisha   41   41   41
riya    52   59   40
om      91   33   93
maitri  92    0   60
shree   59   88   74
niya    56   93   62
tiya    41   41   41
kiya    56    1   56
priya   99   11   37

In [81]:
marks+2

py  fds  cai
jiya     94   56   58
tisha    43   43   43
riya     54   61   42
om       93   35   95
maitri   94    2   62
shree    61   90   76
niya     58   95   64
tiya     43   43   43
kiya     58    3   58
priya   101   13   39

In [ ]:
marks